project:
  type: website
  output-dir: docs

website:
  title: "Zhenpeng Zhang"
  navbar:
    left:
      - href: index.qmd
        text: HomePage
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

